[package]
name = "macros"
version = "0.1.0"
authors = ["Paul Biggar <paul.biggar@gmail.com>"]
edition = "2018"

[dependencies]
proc-macro2 = {version = "1.0.19", features = ["nightly"]}
quote = "1.0"
syn = {version = "1.0.39", features = ["full"]}

[lib]
proc-macro = true
path = "lib.rs"